from DataHandler import DataHandler
from PageHandler import PageHandler
from IndexHandler import IndexHandler
from ListHandler import ListHandler
from LoginHandler import LoginHandler
from LogoutHandler import LogoutHandler
from RegisterHandler import RegisterHandler
from SearchHandler import SearchHandler
from TestHandler import TestHandler
from TemplateHandler import TemplateHandler