application: vroot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: view/images

- url: /css
  static_dir: view/css
  
- url: /js
  static_dir: view/js

- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest